openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API documentation for my Express application
paths:
  /api/question:
    get:
      summary: Example Get endpoint
      description: This endpoint does not require a request body.
      parameters:
        - name: region
          in: query
          required: false
          description: An example query parameter.
          schema:
            type: string
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
