openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API documentation for my Express application
paths:
  /api/question:
    post:
      summary: Example POST endpoint
      description: This endpoint does not require a request body.
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
